// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Q246xkarK16xHE3jg42qYKKxxmV62tM',
    appId: '1:547401977304:web:e4411e0f1b0a5bcb7476ad',
    messagingSenderId: '547401977304',
    projectId: 'finaltest2-3891c',
    authDomain: 'finaltest2-3891c.firebaseapp.com',
    storageBucket: 'finaltest2-3891c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiOQFttvfbjE6BW8MUMke4HvVj8HLFnHc',
    appId: '1:547401977304:android:069b709ba4da35207476ad',
    messagingSenderId: '547401977304',
    projectId: 'finaltest2-3891c',
    storageBucket: 'finaltest2-3891c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB313elaTtpFTcrREtbGkt45SZUMrpCDlk',
    appId: '1:547401977304:ios:956efc144b314bd67476ad',
    messagingSenderId: '547401977304',
    projectId: 'finaltest2-3891c',
    storageBucket: 'finaltest2-3891c.appspot.com',
    androidClientId: '547401977304-ujfj60sbotd10bm6cchovkev4thmdnoe.apps.googleusercontent.com',
    iosClientId: '547401977304-lakhu85j8dhlj2pojs786060lcaikhfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.finaltest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB313elaTtpFTcrREtbGkt45SZUMrpCDlk',
    appId: '1:547401977304:ios:956efc144b314bd67476ad',
    messagingSenderId: '547401977304',
    projectId: 'finaltest2-3891c',
    storageBucket: 'finaltest2-3891c.appspot.com',
    androidClientId: '547401977304-ujfj60sbotd10bm6cchovkev4thmdnoe.apps.googleusercontent.com',
    iosClientId: '547401977304-lakhu85j8dhlj2pojs786060lcaikhfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.finaltest2',
  );
}
